const propertiesDummyData = [
    {
        pgName: "Muskan PG",
        title: "",
        contactPersonName: "Muskan Bansal",
        email: "abc@abc.com",
        mobile: "123",
        addLine1: "abc",
        addLine2: "abc",
        landmark: "acx",
        postalCode: "123",
        address: "acx1",
        providerType: "Owner",
        availableFor: "Girls",
        occupancy: "Double",
        foodMeals: "Exclusive",
        electricity: "Inclusive in Rent",
        roomCooling: "Room Cooler",
        seatsAvailable: "10",
        rent: "6000",
        deposit: "1 month",
        waterSupply: "Normal",
        hotWater: "Available",
        drinkingWater: "Normal",
        safety: "Owner Safety",
        doorOpeningTime: "6am to 10pm",
        laundary: "Self Arranged",
        parking: "Not Available",
        bedType: "Available with box",
        locker: "Available",
        tableChair: "Available",
        internet: "Available Extra Charge",
        cableTV: "Not Available",
    },
]

export default propertiesDummyData;